### ISSUE TITLE
老师，想把体积光的效果放到URP的项目里，怎么操作呢？

### ISSUE THREAD

**Issue by zdpdsg** [SardineFish/SRP-Demos#2]
![image](https://user-images.githubusercontent.com/84756659/125265220-32ce0100-e337-11eb-9c18-f2c220c82b5c.png)
怎么多的脚本吗？这个难度太大了吧，我刚刚才看完unity shader入门精要

**Comment by SardineFish** [comment]
我这个demo是基于 SRP 自己实现的管线做的，要移植到 URP 还需要一些操作，这里面大部分代码是无关体积光的。

**Comment by zdpdsg** [comment]
![image](https://user-images.githubusercontent.com/84756659/125428417-09dafc68-412e-40c5-bc33-dbec8b51f629.png) 明白！但场景里shader都是ForwardDefault，这个Raymarching的shader是在哪使用了啊？我在光源的挂载脚本里也没看到有用到这个shader，还是不太明白，老师是怎么处理光源的。

**Comment by SardineFish** [comment]
这个是在ProjectSettings > Graphics > Render Pipeline 上配置了自定的 RPAsset，然后 RPAsset 是我自己写的渲染管线，上面应该有引用 VolumeLighting 相关的一个模块，Shader 的引用应该在这上面，要么就是我硬编码在代码里了，有点记不清了（

**Comment by zdpdsg** [comment]
渲染管线的编写  《Unity Shader入门精要》并没有教。。。我再琢磨一下吧 谢谢老师！

**Comment by SardineFish** [comment]
这本书当年都还没出 SRP，不知道后续还有没有更新，那这个issue先关了？

**Comment by zdpdsg** [comment]
好的 谢谢
